//! Shared types for upgrade directives and status reporting.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use super::marker::UpgradeMarker;
use super::version::BinaryVersion;

/// Everything a node needs to perform one upgrade. Sent by the leader (or
/// relish, single-node) to `POST /v1/upgrade/apply` as JSON.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpgradeDirective {
    /// Idempotency key, generated by whoever starts the upgrade. Re-sending
    /// a directive with the same id while it is in flight is a no-op.
    pub upgrade_id: String,
    pub target_version: BinaryVersion,
    /// Hex SHA-256 of the binary; also its content address in Pickle.
    pub binary_sha256: String,
    /// Base64 Ed25519 signature from the release key set.
    pub embedded_signature: String,
    /// Base64 Ed25519 signature from the operator's external key.
    /// `None` only for air-gapped (local file) upgrades.
    pub external_signature: Option<String>,
    pub source: BinarySource,
    /// Whether the binary bytes came from the network, independent of how they
    /// are delivered to the node (M5). The single-node network flow downloads
    /// the artefact and stages it as a `LocalFile`, but it is still a network
    /// upgrade and must require the operator's external signature. Verification
    /// treats the upgrade as network when this is set OR the source is network.
    pub network_provenance: bool,
    /// The operator explicitly allowed a target older than the running
    /// version (`relish upgrade start --allow-downgrade`). Without it the
    /// node refuses a downgrade.
    #[serde(default)]
    pub allow_downgrade: bool,
}

/// Where the node obtains the binary bytes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum BinarySource {
    /// Fetch from the Pickle registry, content-addressed by
    /// `binary_sha256`. Network upgrades use this; the external
    /// signature is mandatory.
    Pickle { registry_address: String },
    /// The binary is already at this local path (air-gapped / single-node
    /// `--binary` flow). The embedded signature alone suffices.
    LocalFile { path: PathBuf },
}

impl BinarySource {
    /// Network upgrades demand the external signature; local files don't.
    pub fn is_network(&self) -> bool {
        matches!(self, BinarySource::Pickle { .. })
    }
}

/// One line of `{data_dir}/upgrade/history.jsonl`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpgradeHistoryEntry {
    pub upgrade_id: String,
    pub from_version: BinaryVersion,
    pub to_version: BinaryVersion,
    pub outcome: UpgradeOutcome,
    /// Human-readable detail (failure reason, boot attempts, ...).
    pub detail: String,
    /// Wall-clock time the outcome was recorded.
    pub recorded_at: std::time::SystemTime,
}

/// How a node-level upgrade ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum UpgradeOutcome {
    /// The new version verified and the swap is permanent.
    Committed,
    /// The previous version is back in control.
    Reverted,
    /// The marker was inconsistent and archived without action.
    Abandoned,
}

/// Node-level upgrade status for `GET /v1/upgrade/status`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeUpgradeStatus {
    pub running_version: BinaryVersion,
    /// The in-flight marker, if an upgrade is underway on this node.
    pub in_flight: Option<UpgradeMarker>,
    /// Most recent history entries, newest last (bounded).
    pub history: Vec<UpgradeHistoryEntry>,
}

// ---------------------------------------------------------------------------
// Cluster-level upgrade state (lives in Raft: DesiredState.active_upgrade)
// ---------------------------------------------------------------------------

/// Cluster-wide rolling upgrade state, replicated through Raft so a new
/// leader resumes exactly where the old one stopped — that is how "the
/// leader upgrades last" works at all.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClusterUpgradeState {
    pub upgrade_id: String,
    pub target_version: BinaryVersion,
    pub binary_sha256: String,
    pub embedded_signature: String,
    pub external_signature: Option<String>,
    /// Worker batch size (council members always go one at a time).
    pub parallel: u32,
    pub direction: UpgradeDirection,
    pub phase: ClusterUpgradePhase,
    /// Registry address nodes fetch the binary from (leader's Pickle).
    /// Empty for rollbacks (the binary is already on every node's disk).
    #[serde(default)]
    pub registry_address: String,
    /// Carried into every node's directive: the operator allowed a target
    /// older than what the nodes run.
    #[serde(default)]
    pub allow_downgrade: bool,
    /// Fixed at start from gossip membership; the rolling order walks it.
    pub nodes: Vec<NodeUpgradeRecord>,
}

impl ClusterUpgradeState {
    /// Should the scheduler avoid placing new work on this node right now?
    pub fn is_node_cordoned(&self, node_id: &str) -> bool {
        self.nodes.iter().any(|record| {
            record.node_id == node_id
                && matches!(
                    record.phase,
                    NodeUpgradePhase::Directed | NodeUpgradePhase::Verifying
                )
        })
    }
}

/// Whether the run moves versions forward or back. Rollback walks the
/// rolling order in reverse and skips the download/distribution step.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum UpgradeDirection {
    Upgrade,
    Rollback,
}

/// Where the cluster-level rolling upgrade stands.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ClusterUpgradePhase {
    /// Leader is verifying the binary and distributing it via Pickle.
    Preparing,
    UpgradingWorkers,
    UpgradingCouncil,
    /// Leadership is being handed to an already-upgraded council member.
    TransferringLeadership,
    /// The former leader (now a follower) is being upgraded by the new one.
    UpgradingLeader,
    Completed,
    /// Stopped on failure or by the operator; `upgrade resume` re-enters.
    Paused {
        reason: String,
    },
    /// Ended by the operator from `Paused` without finishing
    /// (`relish upgrade abort`, or a cluster rollback that replaced it).
    /// Terminal: the orchestrator archives it to history. Appended last
    /// because the Raft log encodes enum variants by index.
    Aborted {
        reason: String,
    },
}

/// A node's role at plan time (decides its position in the rolling order).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeRole {
    Worker,
    Council,
    Leader,
}

/// One node's progress within the cluster upgrade.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NodeUpgradeRecord {
    pub node_id: String,
    /// API address for directives and version polling.
    pub address: String,
    pub role: NodeRole,
    /// Populated from the first `/v1/version` poll.
    pub from_version: Option<BinaryVersion>,
    pub phase: NodeUpgradePhase,
    /// When the node entered its current phase (drives stuck-node timeouts).
    #[serde(default)]
    pub since: Option<std::time::SystemTime>,
    /// A still-`Pending` node whose directive hit a transient failure (its
    /// registry or API briefly unreachable). The orchestrator re-sends until
    /// the retry window runs out; `None` once delivered or failed for good.
    #[serde(default)]
    pub directive_retry: Option<DirectiveRetry>,
}

/// Transient directive failures the orchestrator is riding out for one node.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DirectiveRetry {
    /// Attempts so far, all of which failed transiently.
    pub attempts: u32,
    /// When the first attempt failed: the retry window counts from here.
    pub first_failed_at: std::time::SystemTime,
    /// When the latest attempt failed: the backoff counts from here.
    pub last_failed_at: std::time::SystemTime,
    /// What the latest attempt said, for status output and the pause reason.
    pub last_error: String,
}

/// Per-node phase within the cluster upgrade.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeUpgradePhase {
    Pending,
    /// Directive accepted (2xx from /v1/upgrade/apply).
    Directed,
    /// Node reports the upgrade in flight; leader is polling.
    Verifying,
    /// Reports the target version, healthy, and gossip-alive.
    Healthy,
    Failed {
        reason: String,
    },
    RolledBack,
}
